pipeline {
    agent none
    
    environment {
        HOST = 'home.mytest.com@1'
        MVN_IMAGE = 'maven:3-alpine'
        SOURCE_FILE = 'test01/target/app.jar'
        HOST_DEST_DIR = '/data/java-jar/test/test-mvn'
        HOST_DEST_FILENAME = 'app.jar'
        SSH_OS_IMAGE = 'roboxes/centos8:3.6.8'
    }
    stages {
        stage('Build') {
            agent {         
                docker {
                    image "${MVN_IMAGE}"
                    args '-u root -v /root/.m2:/root/.m2'         
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean install package'
            }
        }
        
        stage('Transfer') {
            agent {
                docker {
                    image "${SSH_OS_IMAGE}"
                    args '-u root -v /root/.ssh:/root/.ssh -v $HOST_DEST_DIR:$HOST_DEST_DIR'
                }
            }
            steps {
                sh 'scp $SOURCE_FILE $HOST:${HOST_DEST_DIR}/${HOST_DEST_FILENAME}'
            }
        }
        
        stage('MakeImage') {
            steps {
                sh 'echo MakeImage FINISH'
            }
        }
        
        stage('Deploy') {
            agent {
                image "${SSH_OS_IMAGE}"
                args '-u root -v /root/.ssh:/root/.ssh'
            }
            steps {
                sh 'export DATE=`date +%Y-%m-%d-%H-%M-%S` && \
                    echo $DATE'
            }
        }
    }
}
