pipeline {
    agent none
    
    environment {
        IMAGE = 'maven:3-alpine'
    }
    stages {
        stage('Build') {
            agent {         
                docker {
                    image "${IMAGE}"
                    args '-u root -v /root/.m2:/root/.m2'         
                }     
            }
            steps {
                sh 'mvn clean install'
            }
        }
    }
}
